#!/usr/bin/env php
<?php

$directory = realpath(__DIR__.'/fixture/database');

if (! file_exists("{$directory}/database.sqlite")) {
    copy("{$directory}/database.sqlite.example", "{$directory}/database.sqlite");
}
