#!/usr/bin/env php
<?php

define('TESTBENCH_CORE', true);
define('TESTBENCH_WORKING_PATH', $workingPath = getcwd());

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    // Development environment.
    require __DIR__.'/vendor/autoload.php';
} else {
    // Installation environment.
    require __DIR__.'/../../autoload.php';
}

$filename = Illuminate\Support\LazyCollection::make(function () {
    yield 'testbench.yaml';
    yield 'testbench.yaml.example';
    yield 'testbench.yaml.dist';
})->filter(function ($file) use ($workingPath) {
    return file_exists($workingPath.DIRECTORY_SEPARATOR.$file);
})->first() ?? 'testbench.yaml';

$config = Orchestra\Testbench\Foundation\Config::loadFromYaml(
    $workingPath, $filename, ['providers' => [], 'dont-discover' => []]
);

$commander = new Orchestra\Testbench\Console\Commander($config, $workingPath);

$commander->handle();
