name: analyse

on:
  push:
    branches:
      - '*.x'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analyse:
    runs-on: "ubuntu-latest"
    continue-on-error: false
    strategy:
      matrix:
        php: [8.4]

    name: PHP:${{ matrix.php }} Code Analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite, bcmath, fileinfo
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: "highest"
          composer-options: "--prefer-dist --no-cache"

      - name: Execute Code Style
        run: vendor/bin/pint --test

      - name: Execute Static Code Analysis
        run: vendor/bin/phpstan analyse --verbose

  lint:
    runs-on: "ubuntu-latest"
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        php: [8.4]
        experimental:
          - false

    name: PHP:${{ matrix.php }} Code Lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite, bcmath, fileinfo
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: "highest"
          composer-options: "--prefer-dist --no-cache"

      - name: PHP Lint
        run: php -l ./src
