name: audits

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  audit-dependencies:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - 8.1
          - 8.2
          - 8.3
        experimental:
          - true

    name: PHP${{ matrix.php }} on ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo, :php-psr
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "highest"
          composer-options: "--prefer-dist --prefer-stable --no-cache"

      - name: Installed dependencies
        run: composer show -D

      - name: Audit dependencies
        run: composer audit
