name: parallel-tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
        php:
          - "8.0"
        phpunit:
          - "^9.5.4"
        dependencies:
          - "locked"
          - "lowest"
          - "highest"
        experimental:
          - true

    name: PHP${{ matrix.php }} with PHPUnit${{ matrix.phpunit }} on ${{ matrix.os }} (${{ matrix.dependencies }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Install PHPUnit ${{ matrix.phpunit }}
        run: |
          composer require "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
          composer require "nunomaduro/collision" --dev --no-interaction --no-update
          composer require "brianium/paratest" --dev --no-interaction --no-update

      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache"

      - name: Prepare Testbench
        run: composer run prepare

      - name: Execute tests
        run: ./testbench package:test --parallel
