name: strict-tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  strict-tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - 8.2
          - 8.3
        phpunit:
          - "~10.5.0"
          - "~11.0.0"
          - "~11.1.0"
          - "~11.2.0"
          - "~11.3.0"
          - "~11.4.0"
        dependencies:
          - "highest"
        experimental:
          - false

    name: PHP:${{ matrix.php }} with PHPUnit:${{ matrix.phpunit }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo, :php-psr
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache --with=phpunit/phpunit:${{ matrix.phpunit }}"

      - name: Installed dependencies
        run: |
          composer show -D

      - name: Execute tests (with deprecations)
        run: vendor/bin/phpunit --fail-on-warning --fail-on-deprecation --fail-on-notice --display-deprecations
        env:
          RAY_ENABLED: false
