name: strict-tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  strict-tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - 8.1
          - 8.2
        phpunit:
          - "~10.1.0"
          - "~10.2.0"
        dependencies:
          - "highest"
        experimental:
          - false
        include:
          - os: "ubuntu-latest"
            php: 8.3
            phpunit: "~10.2.0"
            dependencies: "highest"
            experimental: true


    name: PHP${{ matrix.php }} with PHPUnit${{ matrix.phpunit }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Install PHPUnit ${{ matrix.phpunit }}
        run: |
          composer require "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache"
        if: matrix.php <= 8.2

      - name: Install dependencies for PHP 8.3
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache --ignore-platform-req=php"
        if: matrix.php == 8.3

      - name: Installed dependencies
        run: |
          composer show -D

      - name: Execute tests (with deprecations)
        run: vendor/bin/phpunit --fail-on-warning --fail-on-deprecation --fail-on-notice
        env:
          RAY_ENABLED: false
